version: "3.9"
services:
  dev-eskola-db:
    image: postgres
    restart: always
    container_name: dev-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgress:/data/postgres

volumes:
  postgress:
 